title: "とあさのうみ"
description: "toasa のブログです。"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://toasa.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
github_username: toasa

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag